### ISSUE TITLE
Example is not working using HTTP driver because of conflicting Jackson versions in classpath

### ISSUE THREAD

**Issue by mvitz** [liquigraph/spring-boot-example#4]
It seems that the `neo4j-jdbc-http`-Driver comes bundled with Jackson classes. When starting the example with `mvn spring-boot:run` the following error is logged and the application quits immediately:
```
2017-01-17 14:07:07.531 ERROR 23891 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquigraph' defined in class path resource [org/liquigraph/spring/starter/LiquigraphAutoConfiguration$LiquigraphConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1589) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) [spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.3.RELEASE.jar:1.4.3.RELEASE]
	at org.liquigraph.examples.spring.SampleController.main(SampleController.java:44) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:507) [spring-boot-maven-plugin-1.4.3.RELEASE.jar:1.4.3.RELEASE]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:151) ~[jackson-databind-2.8.5.jar:2.8.5]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119) ~[jackson-databind-2.8.5.jar:2.8.5]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79) ~[jackson-databind-2.8.5.jar:2.8.5]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18) ~[jackson-databind-2.8.5.jar:2.8.5]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292) ~[jackson-databind-2.8.5.jar:2.8.5]
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3681) ~[jackson-databind-2.8.5.jar:2.8.5]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3057) ~[jackson-databind-2.8.5.jar:2.8.5]
	at org.neo4j.jdbc.http.driver.Neo4jStatement.toJson(Neo4jStatement.java:70) ~[neo4j-jdbc-driver-3.0.1.jar:na]
	at org.neo4j.jdbc.http.driver.CypherExecutor.executeQueries(CypherExecutor.java:148) ~[neo4j-jdbc-driver-3.0.1.jar:na]
	at org.neo4j.jdbc.http.driver.CypherExecutor.executeQuery(CypherExecutor.java:163) ~[neo4j-jdbc-driver-3.0.1.jar:na]
	at org.neo4j.jdbc.http.HttpConnection.executeQuery(HttpConnection.java:93) ~[neo4j-jdbc-driver-3.0.1.jar:na]
	at org.neo4j.jdbc.http.HttpStatement.execute(HttpStatement.java:58) ~[neo4j-jdbc-driver-3.0.1.jar:na]
	at org.liquigraph.core.io.lock.LiquigraphLock.ensureLockUnicity(LiquigraphLock.java:89) ~[liquigraph-core-3.0.2-SNAPSHOT.jar:na]
	at org.liquigraph.core.io.lock.LiquigraphLock.acquire(LiquigraphLock.java:47) ~[liquigraph-core-3.0.2-SNAPSHOT.jar:na]
	at org.liquigraph.core.io.lock.LockableConnection.acquire(LockableConnection.java:74) ~[liquigraph-core-3.0.2-SNAPSHOT.jar:na]
	at org.liquigraph.core.io.GraphJdbcConnector.connect(GraphJdbcConnector.java:38) ~[liquigraph-core-3.0.2-SNAPSHOT.jar:na]
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:126) ~[liquigraph-core-3.0.2-SNAPSHOT.jar:na]
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:117) ~[liquigraph-core-3.0.2-SNAPSHOT.jar:na]
	at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:71) ~[liquigraph-core-3.0.2-SNAPSHOT.jar:na]
	at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:63) ~[liquigraph-core-3.0.2-SNAPSHOT.jar:na]
	at org.liquigraph.spring.SpringLiquigraph.afterPropertiesSet(SpringLiquigraph.java:52) ~[liquigraph-spring-boot-starter-3.0.2-SNAPSHOT.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1648) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1585) ~[spring-beans-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	... 22 common frames omitted

[WARNING]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:507)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquigraph' defined in class path resource [org/liquigraph/spring/starter/LiquigraphAutoConfiguration$LiquigraphConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1589)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at org.liquigraph.examples.spring.SampleController.main(SampleController.java:44)
	... 6 more
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonGenerator.writeStartObject(Ljava/lang/Object;)V
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:151)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3681)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3057)
	at org.neo4j.jdbc.http.driver.Neo4jStatement.toJson(Neo4jStatement.java:70)
	at org.neo4j.jdbc.http.driver.CypherExecutor.executeQueries(CypherExecutor.java:148)
	at org.neo4j.jdbc.http.driver.CypherExecutor.executeQuery(CypherExecutor.java:163)
	at org.neo4j.jdbc.http.HttpConnection.executeQuery(HttpConnection.java:93)
	at org.neo4j.jdbc.http.HttpStatement.execute(HttpStatement.java:58)
	at org.liquigraph.core.io.lock.LiquigraphLock.ensureLockUnicity(LiquigraphLock.java:89)
	at org.liquigraph.core.io.lock.LiquigraphLock.acquire(LiquigraphLock.java:47)
	at org.liquigraph.core.io.lock.LockableConnection.acquire(LockableConnection.java:74)
	at org.liquigraph.core.io.GraphJdbcConnector.connect(GraphJdbcConnector.java:38)
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:126)
	at org.liquigraph.core.api.MigrationRunner$ConnectionSupplier.get(MigrationRunner.java:117)
	at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:71)
	at org.liquigraph.core.api.Liquigraph.runMigrations(Liquigraph.java:63)
	at org.liquigraph.spring.SpringLiquigraph.afterPropertiesSet(SpringLiquigraph.java:52)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1648)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1585)
	... 22 more
```

I personally consider this a bug by the HTTP driver. They should not include any dependencies and if they do they should move them to an own namespace. I filled an issue ages ago https://github.com/neo4j-contrib/neo4j-jdbc/issues/26 but it was declined...

**Comment by fbiville** [comment]
Si it's either that or https://github.com/neo4j-contrib/neo4j-jdbc/issues/88 with Bolt... Great :-/
